default_platform(:android)

platform :android do
  desc "Deploy a new version to the Google Play Store"
  lane :deploy do
    gradle(task: "assembleRelease")
    upload_to_play_store(track: "production")
  end
end
